
export const SELECT_DAY = 'app/Appointment/SELECT_DAY';
export const SELECT_WEEK = 'app/Appointment/SELECT_WEEK';
export const SELECT_DAY_CALENDAR = 'app/Appointment/SELECT_DAY_CALENDAR';

export const SELECT_APPOINTMENT = 'app/Appointment/SELECT_APPOINTMENT';
export const DESELECT_APPOINTMENT = 'app/Appointment/DESELECT_APPOINTMENT';

export const OPEN_ADDING_APPOINTMENT =
  'app/Appointment/OPEN_ADDING_APPOINTMENT';
export const CLOSE_ADDING_APPOINTMENT =
  'app/Appointment/CLOSE_ADDING_APPOINTMENT';

export const LOAD_MEMBERS = 'App/LOAD_MEMBERS';
export const LOAD_MEMBERS_SUCCESS = 'App/LOAD_MEMBERS_SUCCESS';
export const LOAD_MEMBERS_ERROR = 'App/LOAD_MEMBERS_ERROR';
export const SET_DISPLAYED_MEMBERS = 'App/SET_DISPLAYED_MEMBERS';

export const LOAD_WAITING_APPOINTMENT = 'App/LOAD_WAITING_APPOINTMENT';
export const LOAD_WAITING_APPOINTMENT_SUCCESS =
  'App/LOAD_WAITING_APPOINTMENT_SUCCESS';
export const LOAD_WAITING_APPOINTMENT_ERROR =
  'App/ASSIGN_WAITING_APPOINTMENT_ERROR';

export const LOAD_APPOINTMENTS_BY_MEMBERS = 'App/LOAD_APPOINTMENTS_BY_MEMBERS';
export const LOAD_APPOINTMENTS_BY_MEMBERS_SUCCESS =
  'App/LOAD_APPOINTMENTS_BY_MEMBERS_SUCCESS';

export const LOAD_ALL_APPOINTMENTS =
  'App/LOAD_ALL_APPOINTMENTS';
export const LOAD_APPOINTMENTS_BY_MEMBERS_ERROR =
  'App/LOAD_APPOINTMENTS_BY_MEMBERS_ERROR';

export const ASSIGN_APPOINTMENT = 'App/ASSIGN_APPOINTMENT';
export const ASSIGN_APPOINTMENT_SUCCESS = 'App/ASSIGN_APPOINTMENT_SUCCESS';
export const ASSIGN_APPOINTMENT_ERROR = 'App/ASSIGN_APPOINTMENT_ERROR';

export const MOVE_APPOINTMENT = 'App/MOVE_APPOINTMENT';
export const MOVE_APPOINTMENT_SUCCESS = 'App/MOVE_APPOINTMENT_SUCCESS';
export const MOVE_APPOINTMENT_ERROR = 'App/MOVE_APPOINTMENT_ERROR';

export const PUT_BACK_APPOINTMENT = 'App/PUT_BACK_APPOINTMENT';
export const PUT_BACK_APPOINTMENT_SUCCESS = 'App/PUT_BACK_APPOINTMENT_SUCCESS';
export const PUT_BACK_APPOINTMENT_ERROR = 'App/PUT_BACK_APPOINTMENT_ERROR';

export const CANCEL_APPOINTMENT = 'app/Appointment/CANCEL_APPOINTMENT';
export const CANCEL_APPOINTMENT_SUCCESS =
  'app/Appointment/CANCEL_APPOINTMENT_SUCCESS';
export const CANCEL_APPOINTMENT_ERROR =
  'app/Appointment/CANCEL_APPOINTMENT_ERROR';

export const UPDATE_STATUS_APPOINTMENT =
  'app/Appointment/UPDATE_STATUS_APPOINTMENT';
export const UPDATE_STATUS_APPOINTMENT_SUCCESS =
  'app/Appointment/UPDATE_STATUS_APPOINTMENT_SUCCESS';
export const UPDATE_STATUS_APPOINTMENT_ERROR =
  'app/Appointment/UPDATE_STATUS_APPOINTMENT_ERROR';

export const UPDATE_CALENDAR_INTERVAL =
  'app/Appointment/UPDATE_STATUS_APPOINTMENT_ERROR';

export const CHECK_PHONE_ADD_CUSTOMER = 'app/Appointment/CHECK_PHONE_ADD_CUSTOMER';
export const CHECK_PHONE_ADD_CUSTOMER_SUCCESS = 'app/Appointment/CHECK_PHONE_ADD_CUSTOMER_SUCCESS';
export const CHECK_PHONE_ADD_CUSTOMER_ERROR = 'app/Appointment/CHECK_PHONE_ADD_CUSTOMER_ERROR';

export const ADD_CUSTOMER = 'app/Appointment/ADD_CUSTOMER';
export const ADD_CUSTOMER_SUCCESS = 'app/Appointment/ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_ERROR = 'app/Appointment/ADD_CUSTOMER_ERROR';

export const UPDATE_WAITING_APPOINTMENT = 'UPDATE_WAITING_APPOINTMENT';
export const UPDATE_APPOINTMENT_STATUS = 'UPDATE_APPOINTMENT_STATUS';
export const UPDATE_APPOINTMENT_STATUS_SUCCESS = 'UPDATE_APPOINTMENT_STATUS_SUCCESS';
export const UPDATE_APPOINTMENT_STATUS_ERROR = 'UPDATE_APPOINTMENT_STATUS_ERROR';

export const DISABLE_CALENDAR = 'DISABLE_CALENDAR';
export const LOADING_WAITING = 'LOADING_WAITING';
export const LOADING_CALENDAR = 'LOADING_CALENDAR';

export const TIME_STAFFID = 'TIME_STAFFID';
export const ADD_APPOINTMENT_TO_CALENDAR = 'ADD_APPOINTMENT_TO_CALENDAR';

export const DELETE_EVENT_WAITINGLIST = 'DELETE_EVENT_WAITINGLIST';

export const DELETE_EVENT_WAITINGLIST_SUCCESS = 'DELETE_EVENT_WAITINGLIST_SUCCESS';
export const DELETE_EVENT_WAITINGLIST_ERROR = 'DELETE_EVENT_WAITINGLIST_ERROR';
export const REMOVE_APPOINTMENT_WAITING = 'REMOVE_APPOINTMENT_WAITING'
export const DELETE_WAITING_APPPOINTMENT = 'DELETE_WAITING_APPPOINTMENT'

export const CHANGE_APPOINTMENT_TIME = 'CHANGE_APPOINTMENT_TIME'
export const CHANGE_APPOINTMENT_TIME_SUCCESS = 'CHANGE_APPOINTMENT_TIME_SUCCESS'
export const CHANGE_APPOINTMENT_TIME_ERROR = 'CHANGE_APPOINTMENT_TIME_ERROR'

export const UPDATE_APPOINTMENT_OFFLINE = 'UPDATE_APPOINTMENT_OFFLINE'
export const UPDATE_APPOINTMENT_OFFLINE_SUCCESS = 'UPDATE_APPOINTMENT_OFFLINE_SUCCESS'
export const UPDATE_APPOINTMENT_OFFLINE_ERROR = 'UPDATE_APPOINTMENT_OFFLINE_ERROR'

export const ADD_APPOINTMENT_TO_WAITING = 'ADD_APPOINTMENT_TO_WAITING'
export const ADD_APPOINTMENT_RELOAD_CALENDAR = 'ADD_APPOINTMENT_RELOAD_CALENDAR'

export const ADD_APPOINTMENT_REALTIME = 'ADD_APPOINTMENT_REALTIME'

export const INFO_CHECK_PHONE = 'INFO_CHECK_PHONE'

export const UPDATE_APPOINTMENT_PAID = 'UPDATE_APPOINTMENT_PAID'

export const DELETE_APPOINTMENT_CALENDAR = 'DELETE_APPOINTMENT_CALENDAR'

export const UPDATE_STAFF = 'UPDATE_STAFF'
export const CHECKPINCODE = 'CHECKPINCODE'
export const OPEN_PINCODE = 'OPEN_PINCODE'
export const UPDATE_NEXT_STAFF = 'UPDATE_NEXT_STAFF'
export const UPDATE_NEXT_STAFF_SUCCESS = 'UPDATE_NEXT_STAFF_SUCCESS'
export const UPDATE_USER = 'UPDATE_USER'
export const RENDER_APPOINTMEMT = 'RENDER_APPOINTMEMT'
export const UPDATE_APPOINTMENT_CALENDAR_FRONTEND = 'UPDATE_APPOINTMENT_CALENDAR_FRONTEND'
export const ADD_BLOCKTIME = 'ADD_BLOCKTIME'
export const DELETE_BLOCKTIME = 'DELETE_BLOCKTIME'
export const DELETE_BLOCKTIME_SUCCESSS = 'DELETE_BLOCKTIME_SUCCESSS'
export const GET_BLOCKTIME = 'GET_BLOCKTIME'
export const GET_BLOCKTIME_SUCCESS = 'GET_BLOCKTIME_SUCCESS';
export const GET_APPOINTMENT_OFFLINE = 'GET_APPOINTMENT_OFFLINE';
export const GET_WAITINGLIST_OFFLINE = 'GET_WAITINGLIST_OFFLINE';
export const GET_STAFF_OFFLINE = 'GET_STAFF_OFFLINE';

export const GET_APP_BY_ID = 'GET_APP_BY_ID';
export const GET_APP_BY_ID_SUCCESS = 'GET_APP_BY_ID_SUCCESS';

export const GROUP_APPOINTMENT = 'GROUP_APPOINTMENT';

export const CHECKOUT = 'CHECKOUT';

export const UPDATE_APPOINTMENT_PAID_OFFLINE = 'UPDATE_APPOINTMENT_PAID_OFFLINE';

export const GET_TIME_STAFF_LOGIN = 'GET_TIME_STAFF_LOGIN';
export const GET_TIME_STAFF_LOGIN_SUCCESS = 'GET_TIME_STAFF_LOGIN_SUCCESS';
export const LOAD_STAFF_SORT = 'LOAD_STAFF_SORT';
export const SET_SLIDE_INDEX = 'SET_SLIDE_INDEX';

export const RELOAD_STAFF = 'RELOAD_STAFF';
export const RELOAD_CALENDAR = 'RELOAD_CALENDAR';
export const EDIT_BLOCKTIME = 'EDIT_BLOCKTIME';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const SUBMIT_ADD_APPOINTMENT = 'SUBMIT_ADD_APPOINTMENT';
export const CHANGE_APPOINTMENT = 'CHANGE_APPOINTMENT';

export const SENDLINK_CUSTOMER = 'SENDLINK_CUSTOMER';
export const GET_DETAIL_MERCHANT = 'GET_DETAIL_MERCHANT';
export const SET_DETAIL_MERCHANT = 'SET_DETAIL_MERCHANT';
export const UPDATE_COMPANION = 'UPDATE_COMPANION';
export const IS_LOADING_POPUP = 'IS_LOADING_POPUP';
export const SEARCH_PHONE_COMPANION = 'SEARCH_PHONE_COMPANION';
export const SET_TODAY = 'SET_TODAY';
export const UPDATE_STAFF_APPOINTMENT_PAID = 'UPDATE_STAFF_APPOINTMENT_PAID';
export const TOGGLE_SEARCH_BOX = 'TOGGLE_SEARCH_BOX';
export const SEARCH_CUSTOMER_BOX = 'SEARCH_CUSTOMER_BOX';
export const SET_APPOINTMENT_SEARCH_BOX = 'SET_APPOINTMENT_SEARCH_BOX';
export const SCROLL_TO_APPOINTMENT = 'SCROLL_TO_APPOINTMENT';
export const START_SCROLL_TO_APPOINTMENT = 'START_SCROLL_TO_APPOINTMENT';
export const TOGGLE_NOTIFICATION = 'TOGGLE_NOTIFICATION';

export const COUNT_NOTIFICATION_UNREAD = 'COUNT_NOTIFICATION_UNREAD';
export const SET_COUNT_NOTIFICATION_UNREAD = 'SET_COUNT_NOTIFICATION_UNREAD';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';





