
const SELECT_DAY = 'app/Appointment/SELECT_DAY';
const SELECT_WEEK = 'app/Appointment/SELECT_WEEK';
const SELECT_DAY_CALENDAR = 'app/Appointment/SELECT_DAY_CALENDAR';

const SELECT_APPOINTMENT = 'app/Appointment/SELECT_APPOINTMENT';
const DESELECT_APPOINTMENT = 'app/Appointment/DESELECT_APPOINTMENT';

const OPEN_ADDING_APPOINTMENT =
  'app/Appointment/OPEN_ADDING_APPOINTMENT';
const CLOSE_ADDING_APPOINTMENT =
  'app/Appointment/CLOSE_ADDING_APPOINTMENT';

const LOAD_MEMBERS = 'App/LOAD_MEMBERS';
const LOAD_MEMBERS_SUCCESS = 'App/LOAD_MEMBERS_SUCCESS';
const LOAD_MEMBERS_ERROR = 'App/LOAD_MEMBERS_ERROR';
const SET_DISPLAYED_MEMBERS = 'App/SET_DISPLAYED_MEMBERS';

const LOAD_WAITING_APPOINTMENT = 'App/LOAD_WAITING_APPOINTMENT';
const LOAD_WAITING_APPOINTMENT_SUCCESS =
  'App/LOAD_WAITING_APPOINTMENT_SUCCESS';
const LOAD_WAITING_APPOINTMENT_ERROR =
  'App/ASSIGN_WAITING_APPOINTMENT_ERROR';

const LOAD_APPOINTMENTS_BY_MEMBERS = 'App/LOAD_APPOINTMENTS_BY_MEMBERS';
const LOAD_APPOINTMENTS_BY_MEMBERS_SUCCESS =
  'App/LOAD_APPOINTMENTS_BY_MEMBERS_SUCCESS';

const LOAD_ALL_APPOINTMENTS =
  'App/LOAD_ALL_APPOINTMENTS';
const LOAD_APPOINTMENTS_BY_MEMBERS_ERROR =
  'App/LOAD_APPOINTMENTS_BY_MEMBERS_ERROR';

const ASSIGN_APPOINTMENT = 'App/ASSIGN_APPOINTMENT';
const ASSIGN_APPOINTMENT_SUCCESS = 'App/ASSIGN_APPOINTMENT_SUCCESS';
const ASSIGN_APPOINTMENT_ERROR = 'App/ASSIGN_APPOINTMENT_ERROR';

const MOVE_APPOINTMENT = 'App/MOVE_APPOINTMENT';
const MOVE_APPOINTMENT_SUCCESS = 'App/MOVE_APPOINTMENT_SUCCESS';
const MOVE_APPOINTMENT_ERROR = 'App/MOVE_APPOINTMENT_ERROR';

const PUT_BACK_APPOINTMENT = 'App/PUT_BACK_APPOINTMENT';
const PUT_BACK_APPOINTMENT_SUCCESS = 'App/PUT_BACK_APPOINTMENT_SUCCESS';
const PUT_BACK_APPOINTMENT_ERROR = 'App/PUT_BACK_APPOINTMENT_ERROR';

const CANCEL_APPOINTMENT = 'app/Appointment/CANCEL_APPOINTMENT';
const CANCEL_APPOINTMENT_SUCCESS =
  'app/Appointment/CANCEL_APPOINTMENT_SUCCESS';
const CANCEL_APPOINTMENT_ERROR =
  'app/Appointment/CANCEL_APPOINTMENT_ERROR';

const UPDATE_STATUS_APPOINTMENT =
  'app/Appointment/UPDATE_STATUS_APPOINTMENT';
const UPDATE_STATUS_APPOINTMENT_SUCCESS =
  'app/Appointment/UPDATE_STATUS_APPOINTMENT_SUCCESS';
const UPDATE_STATUS_APPOINTMENT_ERROR =
  'app/Appointment/UPDATE_STATUS_APPOINTMENT_ERROR';

const UPDATE_CALENDAR_INTERVAL =
  'app/Appointment/UPDATE_STATUS_APPOINTMENT_ERROR';

const CHECK_PHONE_ADD_CUSTOMER = 'app/Appointment/CHECK_PHONE_ADD_CUSTOMER';
const CHECK_PHONE_ADD_CUSTOMER_SUCCESS = 'app/Appointment/CHECK_PHONE_ADD_CUSTOMER_SUCCESS';
const CHECK_PHONE_ADD_CUSTOMER_ERROR = 'app/Appointment/CHECK_PHONE_ADD_CUSTOMER_ERROR';

const ADD_CUSTOMER = 'app/Appointment/ADD_CUSTOMER';
const ADD_CUSTOMER_SUCCESS = 'app/Appointment/ADD_CUSTOMER_SUCCESS';
const ADD_CUSTOMER_ERROR = 'app/Appointment/ADD_CUSTOMER_ERROR';

const UPDATE_WAITING_APPOINTMENT = 'UPDATE_WAITING_APPOINTMENT';
const UPDATE_APPOINTMENT_STATUS = 'UPDATE_APPOINTMENT_STATUS';
const UPDATE_APPOINTMENT_STATUS_SUCCESS = 'UPDATE_APPOINTMENT_STATUS_SUCCESS';
const UPDATE_APPOINTMENT_STATUS_ERROR = 'UPDATE_APPOINTMENT_STATUS_ERROR';

const DISABLE_CALENDAR = 'DISABLE_CALENDAR';
const LOADING_WAITING = 'LOADING_WAITING';
const LOADING_CALENDAR = 'LOADING_CALENDAR';

const TIME_STAFFID = 'TIME_STAFFID';
const ADD_APPOINTMENT_TO_CALENDAR = 'ADD_APPOINTMENT_TO_CALENDAR';

const DELETE_EVENT_WAITINGLIST = 'DELETE_EVENT_WAITINGLIST';

const DELETE_EVENT_WAITINGLIST_SUCCESS = 'DELETE_EVENT_WAITINGLIST_SUCCESS';
const DELETE_EVENT_WAITINGLIST_ERROR = 'DELETE_EVENT_WAITINGLIST_ERROR';
const REMOVE_APPOINTMENT_WAITING = 'REMOVE_APPOINTMENT_WAITING'
const DELETE_WAITING_APPPOINTMENT = 'DELETE_WAITING_APPPOINTMENT'

const CHANGE_APPOINTMENT_TIME = 'CHANGE_APPOINTMENT_TIME'
const CHANGE_APPOINTMENT_TIME_SUCCESS = 'CHANGE_APPOINTMENT_TIME_SUCCESS'
const CHANGE_APPOINTMENT_TIME_ERROR = 'CHANGE_APPOINTMENT_TIME_ERROR'

const UPDATE_APPOINTMENT_OFFLINE = 'UPDATE_APPOINTMENT_OFFLINE'
const UPDATE_APPOINTMENT_OFFLINE_SUCCESS = 'UPDATE_APPOINTMENT_OFFLINE_SUCCESS'
const UPDATE_APPOINTMENT_OFFLINE_ERROR = 'UPDATE_APPOINTMENT_OFFLINE_ERROR'

const ADD_APPOINTMENT_TO_WAITING = 'ADD_APPOINTMENT_TO_WAITING'
const ADD_APPOINTMENT_RELOAD_CALENDAR = 'ADD_APPOINTMENT_RELOAD_CALENDAR'

const ADD_APPOINTMENT_REALTIME = 'ADD_APPOINTMENT_REALTIME'

const INFO_CHECK_PHONE = 'INFO_CHECK_PHONE'

const UPDATE_APPOINTMENT_PAID = 'UPDATE_APPOINTMENT_PAID'

const DELETE_APPOINTMENT_CALENDAR = 'DELETE_APPOINTMENT_CALENDAR'

const UPDATE_STAFF = 'UPDATE_STAFF'
const CHECKPINCODE = 'CHECKPINCODE'
const OPEN_PINCODE = 'OPEN_PINCODE'
const UPDATE_NEXT_STAFF = 'UPDATE_NEXT_STAFF'
const UPDATE_NEXT_STAFF_SUCCESS = 'UPDATE_NEXT_STAFF_SUCCESS'
const UPDATE_USER = 'UPDATE_USER'
const RENDER_APPOINTMEMT = 'RENDER_APPOINTMEMT'
const UPDATE_APPOINTMENT_CALENDAR_FRONTEND = 'UPDATE_APPOINTMENT_CALENDAR_FRONTEND'
const ADD_BLOCKTIME = 'ADD_BLOCKTIME'
const DELETE_BLOCKTIME = 'DELETE_BLOCKTIME'
const DELETE_BLOCKTIME_SUCCESSS = 'DELETE_BLOCKTIME_SUCCESSS'
const GET_BLOCKTIME = 'GET_BLOCKTIME'
const GET_BLOCKTIME_SUCCESS = 'GET_BLOCKTIME_SUCCESS';
const GET_APPOINTMENT_OFFLINE = 'GET_APPOINTMENT_OFFLINE';
const GET_WAITINGLIST_OFFLINE = 'GET_WAITINGLIST_OFFLINE';
const GET_STAFF_OFFLINE = 'GET_STAFF_OFFLINE';

const GET_APP_BY_ID = 'GET_APP_BY_ID';
const GET_APP_BY_ID_SUCCESS = 'GET_APP_BY_ID_SUCCESS';

const GROUP_APPOINTMENT = 'GROUP_APPOINTMENT';

const CHECKOUT = 'CHECKOUT';

const UPDATE_APPOINTMENT_PAID_OFFLINE = 'UPDATE_APPOINTMENT_PAID_OFFLINE';

const GET_TIME_STAFF_LOGIN = 'GET_TIME_STAFF_LOGIN';
const GET_TIME_STAFF_LOGIN_SUCCESS = 'GET_TIME_STAFF_LOGIN_SUCCESS';
const LOAD_STAFF_SORT = 'LOAD_STAFF_SORT';
const SET_SLIDE_INDEX = 'SET_SLIDE_INDEX';

const RELOAD_STAFF = 'RELOAD_STAFF';
const RELOAD_CALENDAR = 'RELOAD_CALENDAR';
const EDIT_BLOCKTIME = 'EDIT_BLOCKTIME';
const UPDATE_NOTE = 'UPDATE_NOTE';
const SUBMIT_ADD_APPOINTMENT = 'SUBMIT_ADD_APPOINTMENT';
const CHANGE_APPOINTMENT = 'CHANGE_APPOINTMENT';

const SENDLINK_CUSTOMER = 'SENDLINK_CUSTOMER';


export {
  SELECT_DAY,
  SELECT_WEEK,
  SELECT_DAY_CALENDAR,
  SELECT_APPOINTMENT,
  DESELECT_APPOINTMENT,
  OPEN_ADDING_APPOINTMENT,
  CLOSE_ADDING_APPOINTMENT,
  LOAD_MEMBERS,
  LOAD_MEMBERS_SUCCESS,
  LOAD_MEMBERS_ERROR,
  SET_DISPLAYED_MEMBERS,
  LOAD_WAITING_APPOINTMENT,
  LOAD_WAITING_APPOINTMENT_SUCCESS,
  LOAD_WAITING_APPOINTMENT_ERROR,
  LOAD_APPOINTMENTS_BY_MEMBERS,
  LOAD_APPOINTMENTS_BY_MEMBERS_SUCCESS,
  LOAD_ALL_APPOINTMENTS,
  LOAD_APPOINTMENTS_BY_MEMBERS_ERROR,
  ASSIGN_APPOINTMENT,
  ASSIGN_APPOINTMENT_SUCCESS,
  ASSIGN_APPOINTMENT_ERROR,
  MOVE_APPOINTMENT,
  MOVE_APPOINTMENT_SUCCESS,
  MOVE_APPOINTMENT_ERROR,
  PUT_BACK_APPOINTMENT,
  PUT_BACK_APPOINTMENT_SUCCESS,
  PUT_BACK_APPOINTMENT_ERROR,
  CANCEL_APPOINTMENT,
  CANCEL_APPOINTMENT_SUCCESS,
  CANCEL_APPOINTMENT_ERROR,
  UPDATE_STATUS_APPOINTMENT,
  UPDATE_STATUS_APPOINTMENT_SUCCESS,
  UPDATE_STATUS_APPOINTMENT_ERROR,
  UPDATE_CALENDAR_INTERVAL,
  CHECK_PHONE_ADD_CUSTOMER,
  CHECK_PHONE_ADD_CUSTOMER_SUCCESS,
  CHECK_PHONE_ADD_CUSTOMER_ERROR,
  ADD_CUSTOMER,
  ADD_CUSTOMER_SUCCESS,
  ADD_CUSTOMER_ERROR,
  UPDATE_WAITING_APPOINTMENT,
  UPDATE_APPOINTMENT_STATUS,
  UPDATE_APPOINTMENT_STATUS_SUCCESS,
  UPDATE_APPOINTMENT_STATUS_ERROR,
  DISABLE_CALENDAR,
  LOADING_WAITING,
  LOADING_CALENDAR,
  TIME_STAFFID,
  ADD_APPOINTMENT_TO_CALENDAR,
  DELETE_EVENT_WAITINGLIST,
  DELETE_EVENT_WAITINGLIST_SUCCESS,
  DELETE_EVENT_WAITINGLIST_ERROR,
  REMOVE_APPOINTMENT_WAITING,
  DELETE_WAITING_APPPOINTMENT,
  CHANGE_APPOINTMENT_TIME,
  CHANGE_APPOINTMENT_TIME_SUCCESS,
  CHANGE_APPOINTMENT_TIME_ERROR,
  UPDATE_APPOINTMENT_OFFLINE,
  UPDATE_APPOINTMENT_OFFLINE_SUCCESS,
  UPDATE_APPOINTMENT_OFFLINE_ERROR,
  ADD_APPOINTMENT_TO_WAITING,
  ADD_APPOINTMENT_RELOAD_CALENDAR,
  ADD_APPOINTMENT_REALTIME,
  INFO_CHECK_PHONE,
  UPDATE_APPOINTMENT_PAID,
  DELETE_APPOINTMENT_CALENDAR,
  UPDATE_STAFF,
  CHECKPINCODE,
  OPEN_PINCODE,
  UPDATE_NEXT_STAFF,
  UPDATE_NEXT_STAFF_SUCCESS,
  UPDATE_USER,
  RENDER_APPOINTMEMT,
  UPDATE_APPOINTMENT_CALENDAR_FRONTEND,
  ADD_BLOCKTIME,
  DELETE_BLOCKTIME,
  DELETE_BLOCKTIME_SUCCESSS,
  GET_BLOCKTIME,
  GET_BLOCKTIME_SUCCESS,
  GET_APPOINTMENT_OFFLINE,
  GET_WAITINGLIST_OFFLINE,
  GET_STAFF_OFFLINE,
  GET_APP_BY_ID,
  GET_APP_BY_ID_SUCCESS,
  GROUP_APPOINTMENT,
  CHECKOUT,
  UPDATE_APPOINTMENT_PAID_OFFLINE,
  GET_TIME_STAFF_LOGIN,
  GET_TIME_STAFF_LOGIN_SUCCESS,
  LOAD_STAFF_SORT,
  SET_SLIDE_INDEX,
  RELOAD_STAFF,
  RELOAD_CALENDAR,
  EDIT_BLOCKTIME,
  UPDATE_NOTE,
  SUBMIT_ADD_APPOINTMENT,
  CHANGE_APPOINTMENT,
  SENDLINK_CUSTOMER
}





