/*
 * AppointmentConstants
 * Each action has a corresponding type, which the reducer knows and picks up on.
 * To avoid weird typos between the reducer and the actions, we save them as
 * constants here. We prefix them with 'app/YourComponent' so we avoid
 * reducers accidentally picking up actions they shouldn't.
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'app/YourContainer/YOUR_ACTION_CONSTANT';
 */

export const SELECT_DAY = 'app/Appointment/SELECT_DAY';
export const SELECT_WEEK = 'app/Appointment/SELECT_WEEK';
export const SELECT_DAY_CALENDAR = 'app/Appointment/SELECT_DAY_CALENDAR';

export const SELECT_APPOINTMENT = 'app/Appointment/SELECT_APPOINTMENT';
export const DESELECT_APPOINTMENT = 'app/Appointment/DESELECT_APPOINTMENT';

export const OPEN_ADDING_APPOINTMENT =
  'app/Appointment/OPEN_ADDING_APPOINTMENT';
export const CLOSE_ADDING_APPOINTMENT =
  'app/Appointment/CLOSE_ADDING_APPOINTMENT';

export const LOAD_MEMBERS = 'App/LOAD_MEMBERS';
export const LOAD_MEMBERS_SUCCESS = 'App/LOAD_MEMBERS_SUCCESS';
export const LOAD_MEMBERS_ERROR = 'App/LOAD_MEMBERS_ERROR';
export const SET_DISPLAYED_MEMBERS = 'App/SET_DISPLAYED_MEMBERS';

export const LOAD_WAITING_APPOINTMENT = 'App/LOAD_WAITING_APPOINTMENT';
export const LOAD_WAITING_APPOINTMENT_SUCCESS =
  'App/LOAD_WAITING_APPOINTMENT_SUCCESS';
export const LOAD_WAITING_APPOINTMENT_ERROR =
  'App/ASSIGN_WAITING_APPOINTMENT_ERROR';

export const LOAD_APPOINTMENTS_BY_MEMBERS = 'App/LOAD_APPOINTMENTS_BY_MEMBERS';
export const LOAD_APPOINTMENTS_BY_MEMBERS_SUCCESS =
  'App/LOAD_APPOINTMENTS_BY_MEMBERS_SUCCESS';
export const LOAD_APPOINTMENTS_BY_MEMBERS_ERROR =
  'App/LOAD_APPOINTMENTS_BY_MEMBERS_ERROR';

export const ASSIGN_APPOINTMENT = 'App/ASSIGN_APPOINTMENT';
export const ASSIGN_APPOINTMENT_SUCCESS = 'App/ASSIGN_APPOINTMENT_SUCCESS';
export const ASSIGN_APPOINTMENT_ERROR = 'App/ASSIGN_APPOINTMENT_ERROR';

export const MOVE_APPOINTMENT = 'App/MOVE_APPOINTMENT';
export const MOVE_APPOINTMENT_SUCCESS = 'App/MOVE_APPOINTMENT_SUCCESS';
export const MOVE_APPOINTMENT_ERROR = 'App/MOVE_APPOINTMENT_ERROR';

export const PUT_BACK_APPOINTMENT = 'App/PUT_BACK_APPOINTMENT';
export const PUT_BACK_APPOINTMENT_SUCCESS = 'App/PUT_BACK_APPOINTMENT_SUCCESS';
export const PUT_BACK_APPOINTMENT_ERROR = 'App/PUT_BACK_APPOINTMENT_ERROR';

export const CANCEL_APPOINTMENT = 'app/Appointment/CANCEL_APPOINTMENT';
export const CANCEL_APPOINTMENT_SUCCESS =
  'app/Appointment/CANCEL_APPOINTMENT_SUCCESS';
export const CANCEL_APPOINTMENT_ERROR =
  'app/Appointment/CANCEL_APPOINTMENT_ERROR';

export const UPDATE_STATUS_APPOINTMENT =
  'app/Appointment/UPDATE_STATUS_APPOINTMENT';
export const UPDATE_STATUS_APPOINTMENT_SUCCESS =
  'app/Appointment/UPDATE_STATUS_APPOINTMENT_SUCCESS';
export const UPDATE_STATUS_APPOINTMENT_ERROR =
  'app/Appointment/UPDATE_STATUS_APPOINTMENT_ERROR';

// FIXME: This is hard code for real-time calendar
export const UPDATE_CALENDAR_INTERVAL =
  'app/Appointment/UPDATE_STATUS_APPOINTMENT_ERROR';

  export const CHECK_PHONE_ADD_CUSTOMER = 'app/Appointment/CHECK_PHONE_ADD_CUSTOMER';
  export const CHECK_PHONE_ADD_CUSTOMER_SUCCESS = 'app/Appointment/CHECK_PHONE_ADD_CUSTOMER_SUCCESS';
  export const CHECK_PHONE_ADD_CUSTOMER_ERROR = 'app/Appointment/CHECK_PHONE_ADD_CUSTOMER_ERROR';

  export const ADD_CUSTOMER = 'app/Appointment/ADD_CUSTOMER';
  export const ADD_CUSTOMER_SUCCESS = 'app/Appointment/ADD_CUSTOMER_SUCCESS';
  export const ADD_CUSTOMER_ERROR = 'app/Appointment/ADD_CUSTOMER_ERROR';

  export const UPDATE_WAITING_APPOINTMENT = 'UPDATE_WAITING_APPOINTMENT';
  export const UPDATE_APPOINTMENT_STATUS = 'UPDATE_APPOINTMENT_STATUS';
  export const UPDATE_APPOINTMENT_STATUS_SUCCESS = 'UPDATE_APPOINTMENT_STATUS_SUCCESS';
  export const UPDATE_APPOINTMENT_STATUS_ERROR = 'UPDATE_APPOINTMENT_STATUS_ERROR';
  
  export const DISABLE_CALENDAR = 'DISABLE_CALENDAR';
  export const LOADING_WAITING = 'LOADING_WAITING';
  export const LOADING_CALENDAR = 'LOADING_CALENDAR';

  export const TIME_STAFFID = 'TIME_STAFFID';
  export const ADD_APPOINTMENT_TO_CALENDAR = 'ADD_APPOINTMENT_TO_CALENDAR';

  export const DELETE_EVENT_WAITINGLIST = 'DELETE_EVENT_WAITINGLIST';

  export const DELETE_EVENT_WAITINGLIST_SUCCESS = 'DELETE_EVENT_WAITINGLIST_SUCCESS';
  export const DELETE_EVENT_WAITINGLIST_ERROR = 'DELETE_EVENT_WAITINGLIST_ERROR';
  export const REMOVE_APPOINTMENT_WAITING =  'REMOVE_APPOINTMENT_WAITING'
  export const DELETE_WAITING_APPPOINTMENT =  'DELETE_WAITING_APPPOINTMENT'

  export const CHANGE_APPOINTMENT_TIME =  'CHANGE_APPOINTMENT_TIME'
  export const CHANGE_APPOINTMENT_TIME_SUCCESS =  'CHANGE_APPOINTMENT_TIME_SUCCESS'
  export const CHANGE_APPOINTMENT_TIME_ERROR =  'CHANGE_APPOINTMENT_TIME_ERROR'

  export const UPDATE_APPOINTMENT_OFFLINE =  'UPDATE_APPOINTMENT_OFFLINE'
  export const UPDATE_APPOINTMENT_OFFLINE_SUCCESS =  'UPDATE_APPOINTMENT_OFFLINE_SUCCESS'
  export const UPDATE_APPOINTMENT_OFFLINE_ERROR =  'UPDATE_APPOINTMENT_OFFLINE_ERROR'

  export const LOAD_APPOINTMENT_AGAIN =  'LOAD_APPOINTMENT_AGAIN'
  export const ADD_APPOINTMENT_TO_WAITING =  'ADD_APPOINTMENT_TO_WAITING'
  export const ADD_APPOINTMENT_RELOAD_CALENDAR =  'ADD_APPOINTMENT_RELOAD_CALENDAR'
  
  export const ADD_APPOINTMENT_REALTIME =  'ADD_APPOINTMENT_REALTIME'

  export const INFO_CHECK_PHONE =  'INFO_CHECK_PHONE'

  export const UPDATE_APPOINTMENT_PAID =  'UPDATE_APPOINTMENT_PAID'

  export const DELETE_APPOINTMENT_CALENDAR =  'DELETE_APPOINTMENT_CALENDAR'

  export const UPDATE_STAFF = 'UPDATE_STAFF'
  export const CHECKPINCODE  = 'CHECKPINCODE'
  export const OPEN_PINCODE = 'OPEN_PINCODE'
  export const UPDATE_NEXT_STAFF = 'UPDATE_NEXT_STAFF'
  export const UPDATE_NEXT_STAFF_SUCCESS = 'UPDATE_NEXT_STAFF_SUCCESS'
  export const UPDATE_USER = 'UPDATE_USER'

  

  


